/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as StaysIndexRouteImport } from './routes/stays/index'
import { Route as ApiPublicPaymentsMpesaCallbackRouteImport } from './routes/api/public/payments/mpesa-callback'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIndexRoute = StaysIndexRouteImport.update({
  id: '/stays/',
  path: '/stays/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsMpesaCallbackRoute =
  ApiPublicPaymentsMpesaCallbackRouteImport.update({
    id: '/api/public/payments/mpesa-callback',
    path: '/api/public/payments/mpesa-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRoute
  '/stays/': typeof StaysIndexRoute
  '/api/public/payments/mpesa-callback': typeof ApiPublicPaymentsMpesaCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRoute
  '/stays': typeof StaysIndexRoute
  '/api/public/payments/mpesa-callback': typeof ApiPublicPaymentsMpesaCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRoute
  '/stays/': typeof StaysIndexRoute
  '/api/public/payments/mpesa-callback': typeof ApiPublicPaymentsMpesaCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/stays/' | '/api/public/payments/mpesa-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/stays' | '/api/public/payments/mpesa-callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/stays/'
    | '/api/public/payments/mpesa-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRoute
  StaysIndexRoute: typeof StaysIndexRoute
  ApiPublicPaymentsMpesaCallbackRoute: typeof ApiPublicPaymentsMpesaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays/': {
      id: '/stays/'
      path: '/stays'
      fullPath: '/stays/'
      preLoaderRoute: typeof StaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mpesa-callback': {
      id: '/api/public/payments/mpesa-callback'
      path: '/api/public/payments/mpesa-callback'
      fullPath: '/api/public/payments/mpesa-callback'
      preLoaderRoute: typeof ApiPublicPaymentsMpesaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRoute,
  StaysIndexRoute: StaysIndexRoute,
  ApiPublicPaymentsMpesaCallbackRoute: ApiPublicPaymentsMpesaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
